version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


# volumes:

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - /srv/project/:/srv/project
      - ./nginx/log/:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
    depends_on:
      - php71
      - php74
    networks:
      - frontend
      - backend
    links:
      - php71
      - php74
  php71:
    build:
      context: ./php71
    volumes:
      - /srv/project/:/srv/project
      - ./php71/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php71/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9071:9000"
    networks:
      - frontend
      - backend
  php74:
    build:
      context: ./php74
    volumes:
      - /srv/project/:/srv/project
      - ./php74/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9074:9000"
    networks:
      - frontend
      - backend
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
