version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


# volumes:

services:
  nginx:
    build:
      context: ./nginx
#      args:
    volumes:
      - /srv/project/:/var/www
      - ./nginx/log/:/var/log/nginx
      - ./nginx/vhosts:/etc/nginx/vhosts
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "8888:80"
#    expose:
#    extra_hosts:
#    environment:
#    depends_on:
    networks:
      - frontend
      - backend
#    links:
