version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - /srv/project/:/srv/project
      - ./nginx/log/:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
    depends_on:
      - php71
      - php74
    networks:
      - frontend
      - backend
    links:
      - php71
      - php74
  php71:
    build:
      context: ./php71
    volumes:
      - /srv/project/:/srv/project
      - ./php71/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php71/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9071:9000"
    networks:
      - frontend
      - backend
  php74:
    build:
      context: ./php74
    volumes:
      - /srv/project/:/srv/project
      - ./php74/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9074:9000"
    networks:
      - frontend
      - backend
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
  logstash:
    build:
      context: ./logstash
      args:
        - ELK_VERSION=7.5.1
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline:/usr/share/logstash/pipeline'
    ports:
      - '5001:5001'
    environment:
      LS_JAVA_OPTS: '-Xmx1g -Xms1g'
    networks:
      - frontend
      - backend
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=7.5.1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=workdock-cluster
      - node.name=workdock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=workdock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - frontend
      - backend
  kibana:
    build:
      context: ./kibana
      args:
        - ELK_VERSION=7.5.1
    ports:
      - "5601:5601"
    networks:
      - frontend
      - backend
